# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae8d9bbb8abdcac3a10f869e8414a759d7fb17846585178354cbd3bf1ab49751993e06cb48a70e5ec1856f01d7be5726650b6720019aea2df7e5623f625368e3

test:
  secret_key_base: 78b7441225cf5c248520a606126642fbe2018b587aa9bfd69b98c6f8c36f1a00ccf0696b7d3826373c88298723332a9a08f8ca8ae140c57754ad660c8daa2f77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
